### ISSUE TITLE
Event loop stopped before Future completed

### ISSUE THREAD

**Issue by Toukite** [custom-components/ble_monitor#295]
Hello,

I think this is linked to https://github.com/custom-components/ble_monitor/issues/167, but since I upgraded to Home Assistant OS 5.12 yesterday, I have trouble with my bluetooth temperature sensors.
I don't see any other event that could have cause an issue, before that it was working perfectly well for months.

Now I can see this error multiple times in the logs:
`**ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.**`

By reading the previous issue, I didn't really get what was the solution.

Additional info: I am running "pure" HassOS on RPI 4B, so I don't have access to root or to the linux behind or to commands like hcitool, the only command that seems to work is bluetoothctl, with which I already tried to re-enable everything and repair all devices without success.
Another info, I use an external dongle (I identified its mac address by plugging it/unplugging it and by seing the output of bluetoothctl list command, and I set the external one as default controller with bluetoothctl)

Config:
```
ble_monitor:
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  active_scan: False
  hci_interface:
    - 1
    - 0
  batt_entities: True
  discovery: False
  restore_state: False 
  report_unknown: False
  devices:
    - mac: 'xxx'
      name: 'xxx'
      temperature_unit: C
```

Thanks for the help !

**Comment by Ernst79** [comment]
There were some issues after a supervisor update recently, which need a full restart of the system. So, not only a restart of HA, but of the entire system. 

Could you give this a try first? For most users, this solves the issue.

**Comment by Toukite** [comment]
I did that multiple times already, no luck :(

**Comment by Ernst79** [comment]
Ok, it was worth to try. I see you have two hci devices configured. Can you change this to the external one only?

**Comment by Ernst79** [comment]
With the ssh addon you can get some access to the Linux system, although limited.  You might try the following command, not sure it will work

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3.8\`` 
```

**Comment by Toukite** [comment]
I have this dongle:
https://www.domadoo.fr/fr/interface-domotique/4947-jeedom-dongle-usb-bluetooth.html

As for the hci device, well the problem is that I have no idea which one is correct since I only have access to bluetoothctl command ... I need to be sure that the external one is taken into account and not the RPI one since I have range issues.

**Comment by Toukite** [comment]
![image](https://user-images.githubusercontent.com/42780622/109335979-0a030e80-7863-11eb-91e3-a9e3d0165deb.png)

**Comment by Toukite** [comment]
I will try to downgrade to HassOS 5.11 tonight in order to confirm that the issue is coming from there. I'll let you know

**Comment by Ernst79** [comment]
Run the command without sudo. HassOs is already running as root

**Comment by Toukite** [comment]
I downgraded to 5.11 and everything works fine again

**Comment by Ernst79** [comment]
Ok, that’s strange. Let m.e have a look at the changes

**Comment by Ernst79** [comment]
the only thing I suspect is a firmware update for a raspberry (I assume you have a Pi?). I will try installing Home assistant OS myself on a second raspberry pi 3b

**Comment by Toukite** [comment]
Yes I'm on raspberry pi 4b

**Comment by Ernst79** [comment]
But I doubt that a firmware update is reverted if you return to 5.11. But I will try. I have just downloaded 5.11

**Comment by Toukite** [comment]
Issue is on 5.12 not 5.11

**Comment by Ernst79** [comment]
yes, I know, I want to check myself if it works on 5.11 first, and than do the upgrade

**Comment by Ernst79** [comment]
Installed 5.11, all running fine. 

But it won't let me update. No new update available in the supervisor. `ha os update` doesn't work (`Unexpected server response. Status code:  500`). How did you upgrade?

**Comment by Toukite** [comment]
![Screenshot_20210226-205745](https://user-images.githubusercontent.com/42780622/109348922-7129be80-7875-11eb-84b8-4c6e381b03c6.jpg)
Directly through supervisor's tab
Release note link: https://github.com/home-assistant/operating-system/releases/tag/5.12

**Comment by Ernst79** [comment]
after a full host reboot, it is finally showing the update. I'll continue......

**Comment by Ernst79** [comment]
![image](https://user-images.githubusercontent.com/24375847/109349646-97039300-7876-11eb-9f61-5aa5ab14ed9b.png)

Sorry, couldn't reproduce your issue. It's working fine on my end after the update. 

Next possible steps. 
1. Could you try if it does work with only hci0 (on 5.12)? So, disable hci1. 
2. Another thing we can try is this topic, explaining how to access the underlying Home Assistant OS. 
https://developers.home-assistant.io/docs/operating-system/debugging/

See this topic as well, where it seems that they are able to use hcitool on Home Assistant OS.

**Comment by Toukite** [comment]
Could it be due to the rpi difference (me using a 4b and you a 3 ?)
Also, I did have some values in 5.12, but others that did not come at all, and again others that came but with very sporadic update time (not every 60s as in 5.11)
All of this with same xiaomi round temp device (i have a lot of them) 
And i had the error in the logs too

Maybe try adding more devices on your side and display the last update secondary info to see if you can reproduce over some time ?

I'll check the other post

**Comment by Ernst79** [comment]
In the other topic, it is solved by a command that fixes the reference to the correct python version. Often people update e.g. the venv or docker installation with a certain python version, which is different than the version on the host system If this isn't the same, you get your the errors you showed. But in your case, you are running Home Assistant OS, which should always run the same version of python for HA as the one on the host system. Unless the changed something in 5.12. 

But getting some data is strange, yes. I'll keep an eye on the sensors. I have 3 of them, all report fine so far, no errors.

**Comment by Ernst79** [comment]
![image](https://user-images.githubusercontent.com/24375847/109355794-0f228680-7880-11eb-9d1c-80def627f67f.png)

I managed to login and run some hci commands. I used this method. 

https://developers.home-assistant.io/docs/operating-system/debugging/

You will have to generate ssh rsa keys, put the public key on an usb named CONFIG and upload it to HA (with a reboot, it will be added automatically). The full instructions are given in the link above. Next you can login via putty as `root`, with the private key that you generated. After that, you have to give the command `login` and you will get access to the system. When logged in this way, you can run the commands you can't run via the UI ssh add-on.

**Comment by Ernst79** [comment]
I would like to ask you to check the following 

1. update to 5.12. Check if the error comes back or not
2. Use only hci0. Check if the error disappears
3. Use only hci1. Check if the error disappears

**Comment by Toukite** [comment]
Hi,
So I did the upgrade again + root access to use the hcitool command (so now I know that the one I want to use is indeed hci0), and then I changed ble config to use only hci0
I just did it but for now I don't see any issue, all devices seem to update fine

**Comment by Ernst79** [comment]
Ok, thanks for reporting back. I'll close the issue, if it isn't working in the future or the errors return, just reopen this issue again and we will look further.

**Comment by Toukite** [comment]
Spoke too soon .. system is up since 23 hours and was running fine until 4 hours ago where all my bluetooth sensors stopped updating and I see the error in the logs again...
Before that upgrade of yesterday, everything ran for a week without issues on 5.11
Should I rollback again ?

**Comment by Ernst79** [comment]
Going back is not a solution for the long term. Do you have other components that use Bluetooth?

**Comment by Toukite** [comment]
No I only have a bunch of xiaomi mija temp sensors (round one) that use bluetooth, everything else is zigbee/zwave/wifi
Pb is that my heating system decides what to do based upon those temp sensors ... So it's more than just a confort issue, I can't leave it like that

**Comment by Ernst79** [comment]
I meant other components in HA, like the Bluetooth tracker component. 

What you could try is checking if it works with build in Bluetooth for a couple of days (unplug the dongle). If that works, it might be a malfunctioning dongle. Also check if there are firmware updates for the dongle.

**Comment by Toukite** [comment]
I don't know how to test that bt tracker component :(
I don't think it's the dongle as it has been perfectly working for months (and it is still working if I downgrade the OS)
If nothing can be found here then I think the best course would be to downgrade again and as you said open an issue on os github !

**Comment by Ernst79** [comment]
Yes, I guess so. I’m running out of ideas, sorry.

**Comment by Toukite** [comment]
I created https://github.com/home-assistant/operating-system/issues/1264 in case you want to add details or follow the issue !

**Comment by pvojnisek** [comment]
I have the same issue.
Supervised HA is running on a Samsung NP300 notebook, debian buster.
Everything is working like a charm after a reboot. Some hours later I got the same error message. A no data will come ever from the sensors.

**Comment by Ernst79** [comment]
@pvojnisek Did you recently update python? Did you check the possible solution in https://github.com/custom-components/ble_monitor/issues/167#issuecomment-739541674 

This wasn't a solution for @Toukite, but it worked for others.

**Comment by Ernst79** [comment]
@Toukite To explain a bit more how ble monitor works. We use a slightly modified version of [aioblescan](https://github.com/frawau/aioblescan) (Python 3/asyncio library to listen for BLE advertized packets) to listen to the Bluetooth packets. The error `Event loop stopped before Future completed.` is generated somewhere in the library. Perhaps the developer @frawau of this library can help us. 

I know @Magalex2x14 made small changes to the original aioblescan, which was, if I remember correctly, done for ble messages in the so called "extended" format. The modification is using parts of this [none-merged PR](https://github.com/frawau/aioblescan/pull/30). It doesn't necessarily mean that these modifications cause the problem though.  

Unfortunately, I didn't create this part of the code, so it's a bit hard for me to help. I'm not a real programmer :-), and this part of our code has always been a bit of magic to me.

**Comment by pvojnisek** [comment]
When the bluetooth is not reachable, you type from terminal:

```
$ bluetoothctl
Agent Registered
```

```
# scan on
Failed to start discovery: org.bluez.Error.NotReady
```

**Comment by Ernst79** [comment]
On my working system, is see the two bluetooth radio (internal + dongle). 

```
# bluetoothctl
Agent registered
[CHG] Controller B8:27:EB:77:75:50 Pairable: yes
[CHG] Controller 00:1A:7D:DA:71:15 Pairable: yes
```

So, if it fails, it doesn't show your bluetooth dongle at all?

**Comment by frawau** [comment]
Hi,
I am not using HassOS, so I am not sure what your problem is.  If I am not mistaken, you are using the atcmi plugin. If so could you try the library itself, something like

        python3 -m aioblescan -A

Again, I am not familiar with HassOS, so you may need to create a venv and install aioblescan in that environment to avoid conflicts with Hass. 

Then again, if your bluetooth radio disappears from the system, this could point to a lower level problem.

**Comment by pvojnisek** [comment]
Hi @Ernst79,

> `systemctl status bluetooth`

systemctrl is not available in Home Assistant command line.

```
bash-5.0# bluetoothctl 
Agent registered
[bluetooth]# scan on 
Discovery started
[CHG] Controller 50:B7:C3:4C:AF:B5 Discovering: yes
[CHG] Device xx:35:C1:67:31:EF RSSI: -65
[CHG] Device xx:EC:0A:0D:06:81 RSSI: -89
[CHG] Device xx:C6:81:16:47:65 RSSI: -59
[CHG] Device xx:C6:81:16:47:65 TxPower: 12
```
It looks running.

**Comment by Ernst79** [comment]
For the earlier error,

```
# scan on
Failed to start discovery: org.bluez.Error.NotReady
```

I googled a bit and found the follow things you could try

```
bluetoothctl power on
```

and 

```
rfkill unblock all
```

You could give these commands a try.

**Comment by pvojnisek** [comment]
It is getting strange. It was already unblocked.
```
ash-5.0# rfkill list
1: hci1: bluetooth
        Soft blocked: no
        Hard blocked: no
2: phy0: wlan
        Soft blocked: no
        Hard blocked: no
```
After that I start a scan:
```
ash-5.0# hcitool lescan
LE Scan ...
A4:C1:38:64:22:99 (unknown)
A4:C1:38:64:22:99 ATC_642299
4C:65:A8:DB:4E:02 (unknown)
4C:65:A8:DB:4E:02 MJ_HT_V1
```
And:
```
ash-5.0# bluetoothctl 
Agent registered
[bluetooth]# scan on
Discovery started
[CHG] Controller 50:B7:C3:4C:AF:B5 Discovering: yes
[NEW] Device F4:F5:DB:F7:97:DA xxxxx
```

Looks working from terminal. But in Home Assistant the log looks like this:
```
2021-03-22 13:44:35 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: OS error (hci0): [Errno 19] error while attempting to bind on interface 0: No such device
```

**Comment by Ernst79** [comment]
You can set BLE monitor to connect to hci1 in the options of the BLE monitor integration.

**Comment by pvojnisek** [comment]
Thanks @Ernst79,
That's right. Currently it is running. Let's wait for some hours or days. It was strange that is was stopped working after running ok for a while.

**Comment by pvojnisek** [comment]
The problem still exists. 
```
Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:657
Integration: Passive BLE monitor (documentation)
First occurred: 21:11:55 (13 occurrences)
Last logged: 21:47:59
HCIdump thread: Runtime error while stop scan request on hci1: Event loop stopped before Future completed.
```
And no data is coming anymore.
After this this is the situation:
```
bash-5.0# hcitool lescan
Could not open device: No such device
```
```
bash-5.0# rfkill list
1: hci1: bluetooth
        Soft blocked: no
        Hard blocked: no
2: phy0: wlan
        Soft blocked: no
        Hard blocked: no
```
```
bash-5.0# bluetoothctl 
Agent registered
[bluetooth]# scan on
Failed to start discovery: org.bluez.Error.NotReady
```
```
bash-5.0# rfkill block all
bash-5.0# rfkill unblock all
bash-5.0# bluetoothctl 
Agent registered
[bluetooth]# scan on
Discovery started
[CHG] Controller 50:B7:C3:4C:AF:B5 Discovering: yes
[NEW] Device 8C:C6:81:16:47:65 xxxxx
[NEW] Device 00:EC:0A:0D:06:81 xxxxx
```
```
bash-5.0# rfkill list
1: hci1: bluetooth
        Soft blocked: no
        Hard blocked: no
2: phy0: wlan
        Soft blocked: no
        Hard blocked: no
```
And the Passive BLE monitor in HA started to work again.

Now I will wait for the next outage and I will test this process again.

**Comment by Ernst79** [comment]
It looks like both hcitool and bluetoothctl do not recognize hci1 anymore at a certain moment. I have no idea why, though.

**Comment by pvojnisek** [comment]
Now it stopped again after less than 24 hours of operation. Here is the log:
```
Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:657
Integration: Passive BLE monitor (documentation)
First occurred: 23 March 2021, 08:22:54 (229 occurrences)
Last logged: 12:21:49

HCIdump thread: Runtime error while stop scan request on hci1: Event loop stopped before Future completed.
```

```
$ hcitool lescan
Set scan parameters failed: Operation not permitted
```

```
$ systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset
   Active: active (running) since Mon 2021-03-15 08:10:06 CET; 1 weeks 2 days ag
     Docs: man:bluetoothd(8)
 Main PID: 449 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4213)
   Memory: 2.4M
   CGroup: /system.slice/bluetooth.service
           └─449 /usr/lib/bluetooth/bluetoothd
```

```
$ bluetoothctl 
Agent registered
[bluetooth]# scan on
Failed to start discovery: org.bluez.Error.InProgress
```
```
$ rfkill list
rfkill: /dev/rfkill: Operation not permitted
```

I have no clue what to do. I got some esp32 boards and send sensor data via ESPHome instead.

**Comment by Ernst79** [comment]
I'll close the issue, as you have found a workaround. 

Note that BLE monitor 1.5.0-beta is release, which is now using the MAC address in stead of hci. It might help, although in the background, the mac is still converted to a hci port.

**Comment by Toukite** [comment]
> I'll close the issue, as you have found a workaround.

Can you please tell me what the workaround is ?

**Comment by Ernst79** [comment]
The workaround @pvojnisek is using is using ESPHome. I understand it isn't a solution for BLE monitor, but we couldn't figure out what was wrong. 

I'm under the impression that it has something to do with the Bluetooth installation and/or firmware of the Bluetooth radio. 

I recently had the same error when I tried it on a supervised installation on Debian. I had a lot of troubles getting Bluetooth working on Debian, on a raspberry pi 3b+ (so not getting BLE monitor to work, but getting Bluetooth to work in the first place). And after I got it to work, it was still buggy, with the `Event loop stopped` error. I then tried Home Assistant OS on the same Raspberry, and I had no problem at all. Next I tried in on a supervised installation with Raspberry OS, again no problem at all. 

You have home assistant OS, so it's strange that you have this issue. Unfortunately, I don't have a clue what is wrong, other than that I have often read that Bluetooth can be buggy on a raspberry.

**Comment by klim123123** [comment]
Exactly the same problem with HASS and different usb dongles.
I tried 5x different dongles including Asus USB-BT400.
Randomly i get [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.
Operating System
Home Assistant OS 6.1

**Comment by Toukite** [comment]
Hello,
Reopening as I now have this issue with 5.3.2 version and HA 2021.9 :(

Was working fine for me with OS 5.11 until HA 2021.8

I tried upgrading OS to latest 6.4, but issue appeared after 3hours running fine

I was ok with "not upgrading OS" to keep it running, but now it's becoming "not upgrading OS+HA" and that won't work ... 
Should I be considering replacing all my bt devices (xiaomi temp sensors) with zigbee devices ? Or can I expect a fix ?

Thanks & Regards

**Comment by Ernst79** [comment]
Did you do a full system restart after the update?

**Comment by Toukite** [comment]
I think I have but I have a doubt
Anyway, I just did it to make it work again (reboot host). I also updated ble to 5.3.3. 
For now it works but will let you know in a few hours !

**Comment by Toukite** [comment]
Nope, sensors down after ~2h

**Comment by magyarl89** [comment]
I have the same problem also.

> HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.
> HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.

It works for 2 weeks -> error -> complete restart -> works for 10 hours -> error
I have only one Xiaomi LYWSD03MMC temp sensor (with ATC fw).

My config:
- HW: Gigabyte BRIX GB-BXBT-1900 Mini PC
- Bluetooth: integrated module
- OS: OMV 5.6.13-1
- Kernel: Linux 5.10.0-0.bpo.8-amd64
- HA OS as KVM
- HA Core: 2021.9.4
- HA OS: 6.2

**Comment by 50494554524F** [comment]
didn't see this 3d before, i was opening another 3d... btw... i can confirm that going back to os 5.11 on board bluetooth is/seems stable... core, supervisor and ble_monitor can be upgraded to the latest version

**Comment by Toukite** [comment]
Unfortunately I am not able to rollback to 5.11 with everything else up to date. I have an error message in supervisor saying that 5.11 is no more compatible ...

I am currently trying to switch to an old platform https://www.home-assistant.io/integrations/mitemp_bt. 
==> I disabled BLE integration and rebooted host, and for now I am getting data. 
Unfortunately I don't know how to select the correct HCI interface with this old platform and I think it is using the RPI internal one instead of the dongle (so limited range), but at least I have something...

@Ernst79 @Magalex2x14 would you have any suggestion regarding this ?

**Comment by 50494554524F** [comment]
> Unfortunately I am not able to rollback to 5.11 with everything else up to date. I have an error message in supervisor saying that 5.11 is no more compatible ...
> 
> I am currently trying to switch to an old platform https://www.home-assistant.io/integrations/mitemp_bt. ==> I disabled BLE integration and rebooted host, and for now I am getting data. Unfortunately I don't know how to select the correct HCI interface with this old platform and I think it is using the RPI internal one instead of the dongle (so limited range), but at least I have something...
> 
> @Ernst79 @Magalex2x14 would you have any suggestion regarding this ?

you have only to rollback the os using ssh and the commands

ha os update --version 5.13
and then
ha os update --version 5.11

or download the 5.11 image, update the core to latest version and put back on your configuration files...

**Comment by Toukite** [comment]
@50494554524F Thank you ! Going back to 5.13 first and then to 5.11 works indeed.
I will retry BLE with that configuration to see if it holds (but I initially reopened the issue because I now also had it with 5.11 so ... we'll see !)

**Comment by Ernst79** [comment]
OS agent can be installed from here https://github.com/home-assistant/os-agent.

**Comment by Arakon** [comment]
Reopening this, this the issue seems to be snowballing.. while the fix "overall" works, the event eventually keeps happening so often, that BT is spotty at best and just dead at worst.
![image](https://user-images.githubusercontent.com/12016360/139523200-8c7a344f-f0f0-40a1-9eb5-851868df53de.png)

**Comment by Ernst79** [comment]
In 6.0.1, I have made the auto restart of the BT adapter optional. You can turn it on in the options menu.

**Comment by piio** [comment]
Hi,

From some time (I can't recall when exactly but about month ago) I started to suffer to  similar problem - my ble_monitor integration stopped working after few hours. I can't correlate with specific update of HA or ble_monitor. I tried different versions of ble_monitor (e.g 5.5.2, 5.6.2, 5.8.0, 6.0.1, 6.1.0-beta)

My setup: VM on proxmox with Debian 11 (bluetooth device passed to VM), supervised installation, HA core-2021.11.5, supervisor-2021.10.8

From proxmox, I saw this errors:
[38622.152207] usb 2-1.4.1: new full-speed USB device number 13 using ehci-pci
[38622.279641] usb 2-1.4.1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[38622.279661] usb 2-1.4.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[38622.279669] usb 2-1.4.1: Product: CSR8510 A10
[66230.624660] usb 2-1.4.1: reset full-speed USB device number 13 using ehci-pci
[82787.162813] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.179445] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.196312] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.213196] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.230199] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.247173] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.263807] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.280669] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.297430] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.314420] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.330932] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.347423] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.364172] usb 2-1.4: clear tt 1 (90d2) error -71
[82787.370895] usb 2-1-port4: disabled by hub (EMI?), re-enabling...
[82787.370933] usb 2-1.4: USB disconnect, device number 12
[82787.370942] usb 2-1.4.1: USB disconnect, device number 13
[82788.222175] usb 2-1.4: new high-speed USB device number 14 using ehci-pci
[82788.330775] usb 2-1.4: New USB device found, idVendor=214b, idProduct=7250, bcdDevice= 1.00
[82788.330795] usb 2-1.4: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[82788.330804] usb 2-1.4: Product: USB2.0 HUB
[82788.332266] hub 2-1.4:1.0: USB hub found
[82788.332399] hub 2-1.4:1.0: 4 ports detected
[82788.618186] usb 2-1.4.1: new full-speed USB device number 15 using ehci-pci
[82788.758317] usb 2-1.4.1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[82788.758338] usb 2-1.4.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[82788.758347] usb 2-1.4.1: Product: CSR8510 A10
[82789.393863] Bluetooth: hci0: urb 0000000064039e41 failed to resubmit (2)
[82789.650329] usb 2-1.4.1: reset full-speed USB device number 15 using ehci-pci
[82792.309146] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.326016] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.343011] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.359626] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.376256] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.392757] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.409744] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.426241] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.442749] usb 2-1.4: clear tt 1 (90f2) error -71
[82792.459613] usb 2-1.4: clear tt 1 (90f2) error -71

From VM OS:
[101274.221159] usb 3-2: new full-speed USB device number 6 using uhci_hcd
[101274.402061] usb 3-2: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[101274.402073] usb 3-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[101274.402079] usb 3-2: Product: CSR8510 A10
[126891.373935] usb 3-2: USB disconnect, device number 6
[126894.020116] usb 3-2: new full-speed USB device number 7 using uhci_hcd
[126894.200743] usb 3-2: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[126894.200756] usb 3-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[126894.200762] usb 3-2: Product: CSR8510 A10
[126896.773856] usb 3-2: USB disconnect, device number 7
[126899.415865] usb 3-1: new full-speed USB device number 8 using uhci_hcd
[126899.593365] usb 3-1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[126899.593378] usb 3-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[126899.593383] usb 3-1: Product: CSR8510 A10
[126911.368794] usb 3-1: USB disconnect, device number 8
[126911.803504] usb 3-2: new full-speed USB device number 9 using uhci_hcd
[126914.763646] usb 3-1: new full-speed USB device number 10 using uhci_hcd
[126914.946300] usb 3-1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[126914.946313] usb 3-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[126914.946319] usb 3-1: Product: CSR8510 A10
[126916.691650] usb 3-2: new full-speed USB device number 11 using uhci_hcd
[126916.871252] usb 3-2: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[126916.871264] usb 3-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[126916.871270] usb 3-2: Product: CSR8510 A10
[126916.873735] usb 3-2: can't set config #1, error -32
[171075.503454] usb 3-1: USB disconnect, device number 10
[171077.487202] usb 3-2: USB disconnect, device number 11
[171078.302823] usb 3-2: new full-speed USB device number 12 using uhci_hcd
[171078.484162] usb 3-2: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[171078.484175] usb 3-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[171078.484181] usb 3-2: Product: CSR8510 A10
[171078.775040] usb 3-1: new full-speed USB device number 13 using uhci_hcd
[171078.971670] usb 3-1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[171078.971686] usb 3-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[171078.971692] usb 3-1: Product: CSR8510 A10
[171078.973764] usb 3-1: can't set config #1, error -32
[171080.711027] usb 3-2: USB disconnect, device number 12
[171083.222696] usb 3-2: new full-speed USB device number 14 using uhci_hcd
[171083.400012] usb 3-2: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[171083.400024] usb 3-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[171083.400030] usb 3-2: Product: CSR8510 A10
[173122.382894] usb 3-2: reset full-speed USB device number 14 using uhci_hcd

I tried auto-reset function in newer versions of ble_monitor, it doesn't help me.

When ble_monitor stops to receive new data I saw that hci0 is down (auto restart don't help).
In most cases my workaround was to manually set hci0 up and reload ble_monitor integration in home assistant.
hciconfig hci0 up

Sometimes, when my hci0 interface stopped to respond I removed btusb and loaded it again, then I could set hci0 up and after reload of ble_monitor data started to be received again. In few cases I have to re-add usb device to VM at proxmox level.

Two days ago I observed that when that problem occured I see multiple bluetoothctl select 00:1A:7D:AD:17:0A processes.

I downloaded bluez packages from apline 3.15 and manually installed them in home assistant docker container, removed btusb module and loaded it again, reloaded ble_monitor - from that this problem doesn't occur.

bluez-libs-5.62-r0 x86_64 {bluez} (GPL-2.0-or-later) [installed]
bluez-deprecated-5.62-r0 x86_64 {bluez} (GPL-2.0-or-later) [installed]
bluez-5.62-r0 x86_64 {bluez} (GPL-2.0-or-later) [installed]

Previously that packages was in 5.58-r2 version.

I will verify it again to be sure that that specific change (update of bluez packages in home assistant container) solves problem in my install and I will give feedback.

**Comment by Ernst79** [comment]
That’s good news. Keep us updated,

**Comment by piio** [comment]
After another 2 days (exactly 60h) my ble_monitor integration doesn't stop, it's still working correctly.

I found change in docker image from alpine 3.13 to 3.14 on 24.08.2021 (docker release 2021.08.0), there was change on home-assistant on 13.09.2021 to use this docker release. First home-assistant release using this version of alpine was 2021.9.7 from 18.09.2021 - I think that in my system this problem could start to occur.

https://github.com/home-assistant/docker/commit/e61099e85be7fae319f2c5f281d8a945844b669e
https://github.com/home-assistant/core/pull/56191
https://github.com/home-assistant/core/releases/tag/2021.9.7
Maybe bluez package in that alpine version (bluez-*-5.58-r2) have bug which cause this ussue?

Can anyone verify if updating bluez packages from alpine 3.15 (5.62-r0) or downgrading to versions from 3.13 (5.55-r1) will fix their problem too?

**Comment by piio** [comment]
Unfortunately, the issue started to occur again for me, so this is not connected with bluez packages versions.

**Comment by Magalex2x14** [comment]
I just upgraded Python from 3.8 to 3.9, and I got the following error almost immediately after starting HA:
```
2021-12-05 17:54:30 ERROR (Thread-13) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 582, in run
    self._event_loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```
continued:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 593, in run
    reset_bluetooth(hci)
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 159, in reset_bluetooth
    bluetoothctl_select(mac)
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 95, in bluetoothctl_select
    command = subprocess.run(["bluetoothctl", "select", mac], stderr=subprocess.PIPE, check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bluetoothctl', 'select', '00:00:00:00:00:00']' returned non-zero exit status 1.
```

It was a lack of access rights to the hci interface. The procedure described in the [Step 0 of the installation instruction](https://custom-components.github.io/ble_monitor/Installation#step-0-grant-permissions-for-python-to-have-rootless-access-to-the-hci-interface) solved the problem. I think this is a good addition to the topic as an example of a situation when the cause of the discussed error has nothing to do with a malfunction in the Bluetooth subsystem.

**Comment by EcherArt** [comment]
Weird, but in my case it's not the premission issues, at least not from skipping from step 0:

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``  
[password request]
```
```
sudo getcap `readlink -f \`which python3\``                                                                                                                                            
/usr/bin/python3.9 cap_net_admin,cap_net_raw=eip
```


I'll try to give more info for my case:
I am able to pair to:
- My bluetooth headphones (SVEN),
- Roborock/Xiaomi vacuum cleaner, with Blueman or Bluetoothctl.

I am unable to connect:

- To Quingping alarm clock with Blueman or Bluetoothctl: Both can see it on the scan and can connect to it, neither can pair with it.

My bluetooth is through USB dongle, here are some DMESG logs, I have not found any errors so far:

sudo dmesg | grep blue                                     

```
[   38.987412] audit: type=1131 audit(1638717483.059:71): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=blueman-mechanism comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  311.140097] audit: type=1130 audit(1638717755.340:87): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=blueman-mechanism comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  341.173856] audit: type=1131 audit(1638717785.373:88): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=blueman-mechanism comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2229.717840] audit: type=1131 audit(1638719673.908:159): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2240.991725] audit: type=1130 audit(1638719685.181:160): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2242.134052] audit: type=1130 audit(1638719686.325:165): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=blueman-mechanism comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 2272.193301] audit: type=1131 audit(1638719716.385:170): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=blueman-mechanism comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' 
```


I have a Home Assistant Container, and installed BLE monitor through HACS. It is located in /var/lib/hass but I've edited the permissions for the folder so HACS would work. Current permissions:
`drwxr-xr-x 10 hass hass 4096`

My HA config:

```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
logger:
  default: info
  logs:
    hacs: debug
    custom_components.hacs: debug
    queueman: debug
    aiogithubapi: debug

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points    

device_tracker:
  - platform: bluetooth_tracker
```

And finally, the logs:

`HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter [MAC address] and trying again.`

```
Traceback (most recent call last):
  File "/var/lib/hass/custom_components/ble_monitor/__init__.py", line 582, in run
    self._event_loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/var/lib/hass/custom_components/ble_monitor/__init__.py", line 593, in run
    reset_bluetooth(hci)
  File "/var/lib/hass/custom_components/ble_monitor/bt_helpers.py", line 188, in reset_bluetooth
    rfkill_unblock_bluetooth()
  File "/var/lib/hass/custom_components/ble_monitor/bt_helpers.py", line 84, in rfkill_unblock_bluetooth
    command = subprocess.run(["rfkill", "unblock", "bluetooth"], stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rfkill', 'unblock', 'bluetooth']' returned non-zero exit status 1.
```

Also for some reason, known_devices.yaml  show only neighbour's phone and tv :(

**Comment by Magalex2x14** [comment]
@EcherArt Looking at your configuration, I can assume that the problem is with the active tracker. The Bluetooth interface cannot establish a connection while in scan mode (and vice versa). That is, you have a conflict between two integrations (ble_monitor and bluetooth_tracker) if you have only one bluetooth interface in your system. This situation is described in the FAQ in the section [Conflicts with other components using the same BT interface](https://custom-components.github.io/ble_monitor/faq#conflicts-with-other-components-using-the-same-bt-interface). The FAQ also describes the possibility of using ble_monitor as a [device tracker](https://custom-components.github.io/ble_monitor/faq#how-can-i-use-my-device-as-a-tracker).

**Comment by EcherArt** [comment]
I have removed the following lines from the config as I added them to try to solve the proble (read that it can help somewhere, my bad)
```
device_tracker:
  - platform: bluetooth_tracker
```
but unfortunately the errors stay identical. My integration list is:

- AirVisual (purely cloud services, no bluetooth required)
- HACS
- Home ( Meteorologisk institutt (Met.no))
- Bluetooth Low Energy Monitor
- My Wi-Fi router integration (no bluetooth)
- Xiaomi Miio 
- Xiaomi Miot auto

User interface integrations:
- Simple weather card
- Lovelace Xiaomi Vacuum Map card (in theory, takes information from Xiaomi server and not from Bletooth)

**Comment by EcherArt** [comment]
Small addition: in addition to previous steps, I disabled all integrations but BLE Monitor, the errors stay the same.

**Comment by huuub** [comment]
I have a rpi4 and installed homeassistant via docker with the 
image: ghcr.io/linuxserver/homeassistant

Here is my error. PLease note the last line of it. It is different then the ones here. 

Logger: root
Source: custom_components/ble_monitor/bt_helpers.py:95
Integration: Passive BLE monitor (documentation, issues)
First occurred: 4 december 2021 17:13:41 (4969 occurrences)
Last logged: 15:15:50

Uncaught thread exception
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/__init__.py", line 582, in run
    self._event_loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 593, in run
    reset_bluetooth(hci)
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 159, in reset_bluetooth
    bluetoothctl_select(mac)
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 95, in bluetoothctl_select
    command = subprocess.run(["bluetoothctl", "select", mac], stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'


Ok... I solved it. But for those using the linuxserver image. Thats the cause. Using the original image of homeassistant just works

**Comment by jameselks** [comment]
ZOMG I worked on this for hours and the issue was also the LinuxServer.io image! As soon as I installed the original image `docker pull homeassistant/home-assistant` it worked immediately! Thanks.

**Comment by steals** [comment]
I have the same issue on the lates HA and BLE Monitor installed DietPi

```
Dec 21 17:56:16 DietPi homeassistant[3678]: 2021-12-21 17:56:16 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed. Resetting Bluetooth adapter 00:E0:4C:23:99:87 and tr
ying again.
Dec 21 17:56:16 DietPi homeassistant[3678]: 2021-12-21 17:56:16 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] resetting Bluetooth
Dec 21 17:56:16 DietPi homeassistant[3678]: 2021-12-21 17:56:16 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 0 measuring device(s)
Dec 21 17:56:16 DietPi homeassistant[3678]: 2021-12-21 17:56:16 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
Dec 21 17:56:16 DietPi homeassistant[3678]: 2021-12-21 17:56:16 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl select 00:E0:4C:23:99:87
Dec 21 17:56:17 DietPi homeassistant[3678]: 2021-12-21 17:56:17 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl show.....
Dec 21 17:56:18 DietPi homeassistant[3678]: 2021-12-21 17:56:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] Power state of bluetooth adapter is off before resetting Bluetooth, trying to turn it back on.
Dec 21 17:56:18 DietPi homeassistant[3678]: 2021-12-21 17:56:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] rfkill list bluetooth.....
Dec 21 17:56:18 DietPi homeassistant[3678]: 2021-12-21 17:56:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetooth adapter is not soft blocked before reset
Dec 21 17:56:18 DietPi homeassistant[3678]: 2021-12-21 17:56:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetooth adapter is not hard blocked before reset
Dec 21 17:56:18 DietPi homeassistant[3678]: 2021-12-21 17:56:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl power on.....
Dec 21 17:56:18 DietPi homeassistant[3678]: Changing power on succeeded
Dec 21 17:56:18 DietPi homeassistant[3678]: 2021-12-21 17:56:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] rfkill unblock bluetooth.....
Dec 21 17:56:19 DietPi rfkill[6186]: unblock set for type bluetooth
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl show.....
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] Power state of bluetooth adapter is still off after resetting Bluetooth.
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] rfkill list bluetooth.....
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetooth adapter is not soft blocked after reset
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetooth adapter is not hard blocked after reset
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Scanning will be restarted
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor] 0 HCI events processed for previous period
Dec 21 17:56:24 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Run
Dec 21 17:56:25 DietPi homeassistant[3678]: 2021-12-21 17:56:24 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: connected to hci0
Dec 21 17:57:16 DietPi homeassistant[3678]: 2021-12-21 17:57:16 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
Dec 21 17:57:16 DietPi homeassistant[3678]: 2021-12-21 17:57:16 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter 00:E0:4C:23:99:87 an
d trying again.
Dec 21 17:57:17 DietPi homeassistant[3678]: 2021-12-21 17:57:16 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] resetting Bluetooth
Dec 21 17:57:17 DietPi homeassistant[3678]: 2021-12-21 17:57:17 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 0 measuring device(s)
Dec 21 17:57:17 DietPi homeassistant[3678]: 2021-12-21 17:57:17 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
Dec 21 17:57:17 DietPi homeassistant[3678]: 2021-12-21 17:57:17 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl select 00:E0:4C:23:99:87
Dec 21 17:57:17 DietPi homeassistant[3678]: 2021-12-21 17:57:17 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl show.....
Dec 21 17:57:18 DietPi homeassistant[3678]: 2021-12-21 17:57:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] Power state of bluetooth adapter is off before resetting Bluetooth, trying to turn it back on.
Dec 21 17:57:18 DietPi homeassistant[3678]: 2021-12-21 17:57:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] rfkill list bluetooth.....
Dec 21 17:57:18 DietPi homeassistant[3678]: 2021-12-21 17:57:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetooth adapter is not soft blocked before reset
Dec 21 17:57:18 DietPi homeassistant[3678]: 2021-12-21 17:57:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetooth adapter is not hard blocked before reset
Dec 21 17:57:18 DietPi homeassistant[3678]: 2021-12-21 17:57:18 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] bluetoothctl power on.....
Dec 21 17:57:19 DietPi homeassistant[3678]: Changing power on succeeded
Dec 21 17:57:19 DietPi homeassistant[3678]: 2021-12-21 17:57:19 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] rfkill unblock bluetooth.....
Dec 21 17:57:19 DietPi rfkill[6207]: unblock set for type bluetooth
```

I've followed similar previous thread but with no luck to resolve the current one.

Python version is 3.9.9

homeassistant user has all required permissions as I'm able to connect to Xiaomi thermometer with bluetoothctl

**Comment by Ernst79** [comment]
I have added an FAQ topic with some of the possible solutions for this error. I do understand that this isn't solving the issue for everybody, so if you have additional tips, let me know. 

https://custom-components.github.io/ble_monitor/faq#i-get-a-runtimeerror-event-loop-stopped-before-future-completed

**Comment by madarasz** [comment]
I have a Home Assistant Core installation running on Raspberry Pi. Recently I wanted to upgrade to the latest Home Assistant Core and I had to do some other upgrades, I upped the OS to Raspbian GNU/Linux 11 (bullseye), Python to 3.9.5 and reinstalled the new 
"core-2021.12.5" HA Core. All is working fine since then, expect ble_monitor, which produces such errors every 2 minutes:
```
2021-12-27 08:40:34 ERROR (Thread-9) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter AA:AA:AA:AA:AA:AA and trying again.
2021-12-27 08:40:34 ERROR (Thread-9) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 608, in run
    self._event_loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 619, in run
    reset_bluetooth(hci)
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 188, in reset_bluetooth
    rfkill_unblock_bluetooth()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 84, in rfkill_unblock_bluetooth
    command = subprocess.run(["rfkill", "unblock", "bluetooth"], stderr=subprocess.PIPE, check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rfkill', 'unblock', 'bluetooth']' returned non-zero exit status 1.
```

The Raspberry built-in bluetooth device seems to be working fine though: `hciconfig -a`. Also `bluetoothctl`; `scan on` spits out a nice device list, so bluetooth should be fine for the homeassistant user on an OS level.

I was recommended to go through the possible solutions in the FAQ points here https://custom-components.github.io/ble_monitor/faq#i-get-a-runtimeerror-event-loop-stopped-before-future-completed , but they did not solve my problem.

I also noticed that the low-energy scan command `hcitool -i hci0 lescan` was giving "Set scan parameters failed: Input/output error". Did some digging and it this can be solved by:
```
sudo apt-get install libcap2-bin
sudo setcap 'cap_net_raw,cap_net_admin+eip' `which hcitool`
```
Unfortunately, this did not solve my ble_monitor issue above. But I'm leaving it here, maybe this is the missing piece for someone else.

If anyone is aware of other possible fixes, please keep me posted, thank you.

**Comment by EcherArt** [comment]
I have the same message:
```
hcitool -i hci0 lescan
Set scan parameters failed: Input/output error
```
Unfortunately I am not on a Debian distro and can't check for this exact library as it's missing from repository ( probably it have other name), but I was able to execute the proposed solution

` sudo setcap 'cap_net_raw,cap_net_admin+eip' `which hcitool` 
`

Unfortunately it did not stop the errors from appearing

**Comment by steals** [comment]
@Ernst79 any idea where I can put some debug statements to try to catch the root cause?

**Comment by steals** [comment]
I think i moved forward a bit. Looks like aioblescan lib is never initialized. I've added two print statements before and after this line https://github.com/frawau/aioblescan/blob/cda0902be902f6117de192ea868114ed95f0a024/aioblescan/aioblescan.py#L1801
and when I run `python3 -m aioblescan` command in the console I can see the output of the first print statement, but don't see the second one...

**Comment by steals** [comment]
I've finally found out the root cause... it was permission issues for python...

When home assistant installed in `pyenv` the output of the command `which python3` looks like `/home/homeassistant/.pyenv/shims/python3` but this is not the real link to actual `python3` interpreter. The actual binary placed in the folder like `/home/homeassistant/.pyenv/versions/3.9.9/bin/python3.9` (it might slightly differ depending on the installed python version). So to grant root access to python it's required to run `setcap` command with correct path, i.e. `setcap 'cap_net_raw,cap_net_admin+eip' /home/homeassistant/.pyenv/versions/3.9.9/bin/python3.9`

**Comment by madarasz** [comment]
@steals Awesome, it solved the issue for me. Thank you!
I'm using the Home Assistant Core installation, so I have a Python virtual environment in `/srv/homeassistant/`. `srv/homeassistant/python3` was symlinked to `/usr/local/bin/python3.9`, so this was the solution for me:
```
sudo setcap 'cap_net_raw,cap_net_admin+eip' /usr/local/bin/python3.9
```

**Comment by kasper1221** [comment]
the latest update 6.6.0 (beta) fixed the problem for me thanks!!!

**Comment by Ernst79** [comment]
6.6.0 has been released with some fixes in the auto-restart functionality, thanks to @steals.

I have also updated the FAQ with the instructions that were given by @steals. Could one of you check if the instructions make sense?

**Comment by aletzi1** [comment]
After newest update (6.7.2) this problem reappear. 
No issues with 6.6.0 @Ernst79

**Comment by EcherArt** [comment]
Thank you so, so much! The latest update fixed all of my issues and I was able to autoconnect to my alarm clock!

**Comment by Ernst79** [comment]
Can we close this issue now or are there still people having this issue?

**Comment by aletzi1** [comment]
> Can we close this issue now or are there still people having this issue?

With core 2021.12.8, HACS 1.19.2 and BLE Monitor 6.9 BETA, im having this problem. It got fixed in 6.6.0 but for me, it reappears in 6.7.0 or 6.7.1.. Strange.


Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:617

HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter C8:FF:28:88:F2:5B and trying again.

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:645

HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed. Resetting Bluetooth adapter C8:FF:28:88:F2:5B and trying again.

**Comment by Ernst79** [comment]
And if you go back to 6.6.0, it all works ok?

I don’t get this, nothing really has changed between 6.6.0 and 6.7.0, that could explain it, afaik.

**Comment by aletzi1** [comment]
> And if you go back to 6.6.0, it all works ok?
> 
> I don’t get this, nothing really has changed between 6.6.0 and 6.7.0, that could explain it, afaik.

False alert, i had <6.6 installed by my own mistake, sorry.

**Comment by Toukite** [comment]
Hello,

I'll be upgrading everything by the end of the week and let you know my results asap, seems promising though !!
What was the root cause and solution in the end ?

Regards

**Comment by posreg** [comment]
6.9.2

the error is back... :(

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:654
Integration: Passive BLE monitor (documentation, issues)
First occurred: 07:26:20 (1 occurrences)
Last logged: 07:26:20

HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed..

**Comment by magyarl89** [comment]
I can confirm, still have the errors in the log :(

BLE: 6.9.4
HA Core: 2021.12.8
Home Assistant OS: 7.1

Errors:
```
HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed. Resetting Bluetooth adapter ... and trying again.
Source: custom_components/ble_monitor/__init__.py:645

HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter ... and trying again.
Source: custom_components/ble_monitor/__init__.py:617
```

**Comment by jesuslg123** [comment]
Hi, I have started having the same issue from a week ago:

`Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:626
Integration: Passive BLE monitor (documentation, issues)
First occurred: 18 January 2022, 18:44:42 (281 occurrences)
Last logged: 08:51:21
HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.`


- Home Assistant 2021.12.10
- core-2021.12.10
- BLE: 6.9.4-7.1.2

**Comment by Ernst79** [comment]
Did you check the FAQ? The FAQ gives some tips how to solve this (in most cases)

https://custom-components.github.io/ble_monitor/faq#i-get-a-runtimeerror-event-loop-stopped-before-future-completed

**Comment by poltergejst** [comment]
I got this problem after updating python version. Reconfiguring to the current version of python with 'setpcap' solved this problem.

**Comment by robertomontinaro80** [comment]
I receive this error too on my raspberry pi zero w but I don't understand how to fix it...please help me

**Comment by Ernst79** [comment]
Did you follow all steps in the FAQ for this error? See https://custom-components.github.io/ble_monitor/faq#i-get-a-runtimeerror-event-loop-stopped-before-future-completed

**Comment by robertomontinaro80** [comment]
> Did you follow all steps in the FAQ for this error? See https://custom-components.github.io/ble_monitor/faq#i-get-a-runtimeerror-event-loop-stopped-before-future-completed

I've executed these commands:
sudo apt-get install systemd
sudo apt-get install bluetooth pi-bluetooth bluez
sudo apt-get install rfkill

then these:
bluetoothctl power on
rfkill unblock bluetooth

Restarted HA and now I receive this error:

`This error originated from a custom integration.

Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:662
Integration: Passive BLE monitor (documentation, issues)
First occurred: 8:37:37 PM (1 occurrences)
Last logged: 8:37:37 PM

HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter B8:27:EB:A0:80:22 and trying again.`


`This error originated from a custom integration.

Logger: root
Source: custom_components/ble_monitor/bt_helpers.py:84
Integration: Passive BLE monitor (documentation, issues)
First occurred: 8:37:38 PM (1 occurrences)
Last logged: 8:37:38 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 655, in run
    self._event_loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 669, in run
    reset_bluetooth(hci)
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 188, in reset_bluetooth
    rfkill_unblock_bluetooth()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 84, in rfkill_unblock_bluetooth
    command = subprocess.run(["rfkill", "unblock", "bluetooth"], stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rfkill', 'unblock', 'bluetooth']' returned non-zero exit status 1.
`

**Comment by Ernst79** [comment]
Try to install `bluez-deprecated` and after that, do a full system reboot to make sure everything is loaded correctly.

**Comment by robertomontinaro80** [comment]
> bluez-deprecated

pi@raspberrypi:~ $ pip install bluez-deprecated
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement bluez-deprecated
ERROR: No matching distribution found for bluez-deprecated

**Comment by robertomontinaro80** [comment]
> Try to install `bluez-deprecated` and after that, do a full system reboot to make sure everything is loaded correctly.

pi@raspberrypi:~ $ sudo apt-get install bluez-deprecated
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bluez-deprecated

**Comment by Ernst79** [comment]
Hmm, try the reboot first.

**Comment by robertomontinaro80** [comment]
> Hmm, try the reboot first.

pi@raspberrypi:~ $ sudo reboot
pi@raspberrypi:~ $
Using username "pi".
pi@192.168.1.207's password:
Send automatic password
Linux raspberrypi 5.10.92+ #1514 Mon Jan 17 17:35:21 GMT 2022 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Jan 30 20:01:39 2022
pi@raspberrypi:~ $ sudo apt-get install bluez-deprecated
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bluez-deprecated


rebooted still the same message. Is the command to install bluez-deprecated correct?

**Comment by Ernst79** [comment]
I'm not sure you still need it. Lets first try some other things. Did you run the following command?

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
```

**Comment by robertomontinaro80** [comment]
pi@raspberrypi:~ $ sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
pi@raspberrypi:~ $ sudo getcap `readlink -f \`which python3\``
/usr/bin/python3.9 cap_net_admin,cap_net_raw=eip
pi@raspberrypi:~ $ sudo reboot
pi@raspberrypi:~ $

I love you man...It worked....great and thanks for the support...really appreciate...great and gentle....thanks a lot :)

**Comment by Ernst79** [comment]
No problem, you are welcome

**Comment by robertomontinaro80** [comment]
> No problem, you are welcome

Just a question...now I see the sensor with unknown values for temp and humidity...Is it normal?

**Comment by Ernst79** [comment]
Which sensor? Maybe it needs an encryption key

**Comment by robertomontinaro80** [comment]
> Which sensor? Maybe it needs an encryption key

the sensor is the xiaomi mi temperature and humidity monitor 2 the little one squared. You are right It needs an encryption key. I'm searching for..

**Comment by Ernst79** [comment]
Here are some tips how to get it. https://custom-components.github.io/ble_monitor/faq#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key

**Comment by robertomontinaro80** [comment]
> Here are some tips how to get it. https://custom-components.github.io/ble_monitor/faq#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key

Thanks man, I've tried the TelinkFlasher solution. Now I don't see any error. Let's wait for the values. It could need 10 minutes if I understand. Thanks for the support. I sponsored you because you deserve it :)

**Comment by Toukite** [comment]
Hello,
After about 15d running with latest versions of everything (OS / HA / BLE, ...), I have not seen this issue anymore.
So I believe that this issue can be closed now !
Thanks a lot @Ernst79, it took time but it wasn't easy and we finally made it, that's great !!
