### ISSUE TITLE
Config options BT interface and report unknown do not work anymore

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#543]
HA 2021.11 seems to break the configuration menu of BLE monitor (both the option flow as well as the initial configuration after a new installation). 

**Observed behavior**
If you open the options of BLE monitor, bt_interface is not selected anymore.

![image](https://user-images.githubusercontent.com/24375847/140189000-3ac95e84-a82d-4b76-b4f0-c25f9056b2cd.png)

Also report_unkown is empty. 

![image](https://user-images.githubusercontent.com/24375847/140189043-90b40c86-e8c7-4b53-9dca-1c1292d6fa2e.png)

Selecting a bt_interface is returning an error 

![image](https://user-images.githubusercontent.com/24375847/140189077-f57b360a-f706-4539-87a0-99b293ee737c.png)

No errors in the logs, 

**Findings so far**
- Everything seems to work fine on HA 2021.10.7
- Selecting no BT interface seems to "select" the first BT interface anyways and is the only way to continue now. 
- Changing `cv.multi_select` to `vol.In` in the code for the bt_interface option makes the config flow to continue (although bt_interface isn't a list than anymore (can be fixed) and it will only allow you to select one BT interface (unwanted). I suspect some config validation issue is causing this issue
- `report unknown` seems to only have an issue with the option `False`. Changing `False` to "Off" in the code fixes the issue.

**Comment by big23** [comment]
Same problem here...

**Comment by Ernst79** [comment]
Merging the issue by @hurricup from #544 into this issue. 


Installed by cloning master and copying dir with component.

Just trying to install component to the HA, and getting error: 

```
styles.ts:365 POST http://192.168.0.100:8123/api/config/config_entries/flow/f69d350f576342a093f2b97d9319165d 400 (Bad Request)
I @ styles.ts:365
(anonymous) @ styles.ts:365
callApi @ styles.ts:365
f @ search-input.ts:19
value @ step-flow-form.ts:69
handleEvent @ styles.ts:365
```

![image](https://user-images.githubusercontent.com/2811330/140387886-ee689e66-fe41-4571-b876-9696b3ec16c6.png)


## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.9.16-jethubj80
arch | aarch64
timezone | Europe/Moscow

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by happyme531** [comment]
Same issue.

**Comment by Ernst79** [comment]
Some progress, I finally found the error. The config validation of the BT interface should be a dictionary instead of a list. I hope to make a fix this weekend.

**Comment by Ernst79** [comment]
Could you try 5.8.0-beta. It should fix the issue with the BT interface not being able to select.

**Comment by hurricup** [comment]
Ok. Configuration state passed. Still waiting for devices to appear in the integration.
Still: 
- Looks like reset timer is not saved for a device. Tried to set 0 but still have 35

As first time user - would be nice to notify user somehow that we I need to wait for some time for devices to appear. This is kinda confusing.  Btw, just curious - why so long?

**Comment by hurricup** [comment]
Devices appeared and looks working. Thank you very much!

**Comment by Ernst79** [comment]
It depends on the sensor how long it takes before a sensor shows up. E.g. LYWSD03MMC only broadcasts once per 10 minutes, so it can take 10 minutes before it knows that sensor is present.

**Comment by hurricup** [comment]
Btw, for some reason this version is not visible in HACS

![image](https://user-images.githubusercontent.com/2811330/140602251-f948f96a-715d-44e1-8f1d-8cd6054319b6.png)

**Comment by Ernst79** [comment]
That's strange, I can see all the beta's. In your case, you don't see any beta version, perhaps it has to sync. 

![image](https://user-images.githubusercontent.com/24375847/140602425-6b6b1781-5e6f-4a48-b7b3-56b24d13633b.png)

Anyway, I have released 5.8.0 as final. 

I will look into the other issue of report_unkown and the reset_timer. Some questions:

- Are you not able to set it to anything different than 35 seconds, or only not to 0
- If you set it to e.g. 5 seconds, does it reset after 5 seconds or 35 seconds (the reason I'm asking is because I suspect that opening the option window will place the the default value back, but that changing the value should work after clicking submit.

**Comment by Ernst79** [comment]
All should be fixed in 5.9.0-beta, please give it a try.

**Comment by hurricup** [comment]
Unrelated to this issue, but I don't see battery sensor on the dashboard (LYWSD03MMC).
I'm pretty new to all of this, so probably this is intentional.
Should diagnostics present on the dashboard?

**Comment by Ernst79** [comment]
I assume you have HA 2021.11 and are using the automatically generated Lovelace user interface. Starting from 2021.11, they make a difference in the actual sensor measurement (e.g. temperature, humidity for our sensor) and sensors that show diagnostics of the device itself (e.g. battery). See for more explanation https://www.home-assistant.io/blog/2021/11/03/release-202111/#entity-categorization. The first category will be added to the automatically generated UI, the last won’t. But you can, of course, add the battery sensor to the Lovelace user interface manually.

**Comment by hurricup** [comment]
Yes I do. Thank you!

**Comment by luisleonardo** [comment]
> All other issues should be fixed in 5.9.0-beta, please give it a try. I also added some extra's.
> 
> ## Changes
> * Add `entity_category` (diagnostic) to RSSI, battery and voltage sensors.
> * Bump aioblescan to 0.2.9
> * Fix `reset_timer` = `0` returning to default value (`35`) when reopening the device options menu. (Fix for [Config options BT interface and report unknown do not work anymore #543](https://github.com/custom-components/ble_monitor/issues/543))
> * Fix for empty `report_unkown` when selecting `False` when reopening the options menu (Fix for [Config options BT interface and report unknown do not work anymore #543](https://github.com/custom-components/ble_monitor/issues/543))
> * Show both the MAC and hci number in the UI for easier selecting the Bluetooth adapter
> 
> ![image](https://user-images.githubusercontent.com/24375847/140615747-be415a3c-97ad-47aa-ad2e-4e47fb9e4145.png)

I installed the new 5.9.0-beta but still get the "User input malformed" message:
![image](https://user-images.githubusercontent.com/4042791/140754614-46902708-89d6-42bb-9c9a-562b9ffd6b45.png)

**Comment by Ernst79** [comment]
Which option did you change, when you got this error? 

Also try hitting ctrl+F5 a couple of times, perhaps it has some old info in the browsers cache.

**Comment by luisleonardo** [comment]
I am trying to change my Bluetooth device (I've migrated my installation from another host), but this all happens if I just open the options and press save without making any changes.

I already tried to empty the cache and hard reload several times.

**Comment by Ernst79** [comment]
Does it also happen when you do make a change?

**Comment by luisleonardo** [comment]
Yes. If I select the new Bluetooth Mac Address I got the error. If I try to add new devices I got the error. Doesn't matter my option, it always results in the "user input malformed" message.

PS: This is also happening with other integrations like (Adaptive Lighting is a good example).

**Comment by luisleonardo** [comment]
By the way, id there a place where I can manually change the Bluetooth Mac Address so I can have all my devices back again?

**Comment by Ernst79** [comment]
Strange that it also happens in other integrations. I'm going to check it on my main HA production system again. 

About changing the BT mac address, never tried, but should be possible if I read this. 

https://scribles.net/changing-a-bluetooth-device-address-on-raspberry-pi/

**Comment by Ernst79** [comment]
ah, found the same issue. You can solve it by selecting "Report Unknown Devices" to Off (its probably empty right now). 

![image](https://user-images.githubusercontent.com/24375847/140764801-afddd83a-dfca-4ae5-8312-76a117dd6cde.png)

**Comment by luisleonardo** [comment]
> About changing the BT mac address, never tried, but should be possible if I read this.
> 
> https://scribles.net/changing-a-bluetooth-device-address-on-raspberry-pi/

I don't want to change my Bluetooth address, I want to update the integration configuration.
I changed my installation to another host and now I have to set the Passive BLE configuration to the new mac address of the new host.

**Comment by luisleonardo** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/4042791/140766272-007e5817-e007-4a6a-81bc-bb201cccd33a.png)

**Comment by Ernst79** [comment]
Very very strange, I have the exact same settings. Works fine. Perhaps try to delete the integration, restart HA and re-add it. 

![image](https://user-images.githubusercontent.com/24375847/140768777-1cdddd05-28e8-4391-ba89-84f90086c828.png)

**Comment by luisleonardo** [comment]
Integration removed, host restarted, re-added the beta integration and everything appears to be ok now.

Thanks :)

**Comment by Ernst79** [comment]
5.9.0 has been released, closing this issue
